### ISSUE TITLE
Cannot Install on ASUS Tinker Board with Linaro (Ubuntu) OS

### ISSUE THREAD

**Issue by jalanjarosz** [imrahil/OctoPrint-NavbarTemp#59]
pip install "https://github.com/imrahil/OctoPrint-NavbarTemp/archive/master.zip"

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Collecting https://github.com/imrahil/OctoPrint-NavbarTemp/archive/master.zip
  Downloading https://github.com/imrahil/OctoPrint-NavbarTemp/archive/master.zip
     / 368kB 4.4MB/s

Collecting OctoPrint (from OctoPrint-NavbarTemp==0.11)
  ERROR: Could not find a version that satisfies the requirement OctoPrint (from OctoPrint-NavbarTemp==0.11) (from versions: none)

ERROR: No matching distribution found for OctoPrint (from OctoPrint-NavbarTemp==0.11)

**Comment by jalanjarosz** [comment]
Here is some additional information from Octoprint plug-in log:

```
> > 2019-04-30 21:29:54,532   /home/linaro/OctoPrint/venv/bin/python -m pip install https://github.com/imrahil/OctoPrint-NavbarTemp/archive/master.zip --no-cache-dir
> 2019-04-30 21:29:56,069 ! DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> 2019-04-30 21:29:56,850 > Collecting https://github.com/imrahil/OctoPrint-NavbarTemp/archive/master.zip
> 2019-04-30 21:29:56,851 > Downloading https://github.com/imrahil/OctoPrint-NavbarTemp/archive/master.zip
> 2019-04-30 21:29:58,337 > Requirement already satisfied: OctoPrint in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint-NavbarTemp==0.11) (1.3.10)
> 2019-04-30 21:29:58,337 > Requirement already satisfied: pyserial<3.5,>=3.4 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (3.4)
> 2019-04-30 21:29:58,337 > Requirement already satisfied: pylru<1.1,>=1.0.9 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.0.9)
> 2019-04-30 21:29:58,338 > Requirement already satisfied: semantic-version<2.5,>=2.4.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (2.4.2)
> 2019-04-30 21:29:58,338 > Requirement already satisfied: future<0.16,>=0.15.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.15.2)
> 2019-04-30 21:29:58,338 > Requirement already satisfied: scandir<1.4,>=1.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.3)
> 2019-04-30 21:29:58,338 > Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.6.5)
> 2019-04-30 21:29:58,338 > Requirement already satisfied: futures<3.2,>=3.1.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (3.1.1)
> 2019-04-30 21:29:58,339 > Requirement already satisfied: rsa<3.3,>=3.2.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (3.2.3)
> 2019-04-30 21:29:58,339 > Requirement already satisfied: Flask-Assets<0.11,>=0.10 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.10)
> 2019-04-30 21:29:58,339 > Requirement already satisfied: netaddr<0.8,>=0.7.19 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.7.19)
> 2019-04-30 21:29:58,339 > Requirement already satisfied: tornado==4.5.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (4.5.3)
> 2019-04-30 21:29:58,340 > Requirement already satisfied: flask<0.11,>=0.10.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.10.1)
> 2019-04-30 21:29:58,340 > Requirement already satisfied: Click<6.3,>=6.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (6.2)
> 2019-04-30 21:29:58,340 > Requirement already satisfied: regex!=2018.11.6 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (2019.4.14)
> 2019-04-30 21:29:58,340 > Requirement already satisfied: chainmap<1.1,>=1.0.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.0.3)
> 2019-04-30 21:29:58,340 > Requirement already satisfied: wrapt<1.11,>=1.10.11 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.10.11)
> 2019-04-30 21:29:58,341 > Requirement already satisfied: PyYAML<3.11,>=3.10 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (3.10)
> 2019-04-30 21:29:58,341 > Requirement already satisfied: monotonic<1.4,>=1.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.3)
> 2019-04-30 21:29:58,341 > Requirement already satisfied: frozendict<1.3,>=1.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.2)
> 2019-04-30 21:29:58,341 > Requirement already satisfied: netifaces<0.11,>=0.10.6 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.10.9)
> 2019-04-30 21:29:58,341 > Requirement already satisfied: pkginfo<1.5,>=1.4.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (1.4.2)
> 2019-04-30 21:29:58,342 > Requirement already satisfied: watchdog<0.9,>=0.8.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.8.3)
> 2019-04-30 21:29:58,342 > Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (2.6.1)
> 2019-04-30 21:29:58,342 > Requirement already satisfied: feedparser<5.3,>=5.2.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (5.2.1)
> 2019-04-30 21:29:58,342 > Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.2.11)
> 2019-04-30 21:29:58,342 > Requirement already satisfied: requests<3,>=2.18.4 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (2.21.0)
> 2019-04-30 21:29:58,343 > Requirement already satisfied: websocket-client<0.41,>=0.40.0 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.40.0)
> 2019-04-30 21:29:58,343 > Requirement already satisfied: werkzeug<0.9,>=0.8.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.8.3)
> 2019-04-30 21:29:58,343 > Requirement already satisfied: psutil<5.5,>=5.4.6 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (5.4.8)
> 2019-04-30 21:29:58,343 > Requirement already satisfied: Jinja2<2.9,>=2.8.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (2.8.1)
> 2019-04-30 21:29:58,344 > Requirement already satisfied: emoji<0.5,>=0.4.5 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.4.5)
> 2019-04-30 21:29:58,344 > Requirement already satisfied: Flask-Babel<0.10,>=0.9 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.9)
> 2019-04-30 21:29:58,344 > Requirement already satisfied: sarge==0.1.5post0 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.1.5.post0)
> 2019-04-30 21:29:58,344 > Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (0.3.5)
> 2019-04-30 21:29:58,345 > Requirement already satisfied: markdown<2.7,>=2.6.9 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from OctoPrint->OctoPrint-NavbarTemp==0.11) (2.6.11)
> 2019-04-30 21:29:58,345 > Requirement already satisfied: Unidecode<0.05,>=0.04.14 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-NavbarTemp==0.11) (0.4.21)
> 2019-04-30 21:29:58,345 > Requirement already satisfied: pyasn1>=0.1.3 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from rsa<3.3,>=3.2.3->OctoPrint->OctoPrint-NavbarTemp==0.11) (0.4.5)
> 2019-04-30 21:29:58,345 > Requirement already satisfied: webassets>=0.10 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-NavbarTemp==0.11) (0.12.1)
> 2019-04-30 21:29:58,345 > Requirement already satisfied: singledispatch in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-NavbarTemp==0.11) (3.4.0.3)
> 2019-04-30 21:29:58,346 > Requirement already satisfied: certifi in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-NavbarTemp==0.11) (2019.3.9)
> 2019-04-30 21:29:58,346 > Requirement already satisfied: backports-abc>=0.4 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-NavbarTemp==0.11) (0.5)
> 2019-04-30 21:29:58,346 > Requirement already satisfied: itsdangerous>=0.21 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from flask<0.11,>=0.10.1->OctoPrint->OctoPrint-NavbarTemp==0.11) (1.1.0)
> 2019-04-30 21:29:58,346 > Requirement already satisfied: argh>=0.24.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-NavbarTemp==0.11) (0.26.2)
> 2019-04-30 21:29:58,346 > Requirement already satisfied: pathtools>=0.1.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-NavbarTemp==0.11) (0.1.2)
> 2019-04-30 21:29:58,347 > Requirement already satisfied: six>=1.5 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from python-dateutil<2.7,>=2.6.1->OctoPrint->OctoPrint-NavbarTemp==0.11) (1.12.0)
> 2019-04-30 21:29:58,347 > Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-NavbarTemp==0.11) (1.24.2)
> 2019-04-30 21:29:58,347 > Requirement already satisfied: idna<2.9,>=2.5 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-NavbarTemp==0.11) (2.8)
> 2019-04-30 21:29:58,347 > Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-NavbarTemp==0.11) (3.0.4)
> 2019-04-30 21:29:58,347 > Requirement already satisfied: MarkupSafe in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from Jinja2<2.9,>=2.8.1->OctoPrint->OctoPrint-NavbarTemp==0.11) (1.1.1)
> 2019-04-30 21:29:58,348 > Requirement already satisfied: speaklater>=1.2 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-NavbarTemp==0.11) (1.3)
> 2019-04-30 21:29:58,348 > Requirement already satisfied: Babel>=1.0 in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-NavbarTemp==0.11) (2.6.0)
> 2019-04-30 21:29:58,348 > Requirement already satisfied: blinker in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-NavbarTemp==0.11) (1.4)
> 2019-04-30 21:29:58,348 > Requirement already satisfied: pytz>=0a in /home/linaro/OctoPrint/venv/lib/python2.7/site-packages (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-NavbarTemp==0.11) (2019.1)
> 2019-04-30 21:29:58,348 > Building wheels for collected packages: OctoPrint-NavbarTemp
> 2019-04-30 21:29:58,349 > Building wheel for OctoPrint-NavbarTemp (setup.py): started
> 2019-04-30 21:29:59,357 ! ERROR: Error checking for conflicts.
> 2019-04-30 21:29:59,358 ! Traceback (most recent call last):
> 2019-04-30 21:29:59,366 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 524, in _warn_about_conflicts
> 2019-04-30 21:29:59,366 ! package_set, _dep_info = check_install_conflicts(to_install)
> 2019-04-30 21:29:59,367 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
> 2019-04-30 21:29:59,367 ! package_set, _ = create_package_set_from_installed()
> 2019-04-30 21:29:59,367 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 47, in create_package_set_from_installed
> 2019-04-30 21:29:59,368 ! package_set[name] = PackageDetails(dist.version, dist.requires())
> 2019-04-30 21:29:59,368 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2727, in requires
> 2019-04-30 21:29:59,368 ! dm = self._dep_map
> 2019-04-30 21:29:59,369 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _dep_map
> 2019-04-30 21:29:59,369 ! self.__dep_map = self._compute_dependencies()
> 2019-04-30 21:29:59,369 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _compute_dependencies
> 2019-04-30 21:29:59,369 ! for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
> 2019-04-30 21:29:59,370 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3005, in _parsed_pkg_info
> 2019-04-30 21:29:59,370 ! metadata = self.get_metadata(self.PKG_INFO)
> 2019-04-30 21:29:59,370 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1419, in get_metadata
> 2019-04-30 21:29:59,370 ! value = self._get(self._fn(self.egg_info, name))
> 2019-04-30 21:29:59,371 ! File "/home/linaro/OctoPrint/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1607, in _get
> 2019-04-30 21:29:59,371 ! with open(path, 'rb') as stream:
> 2019-04-30 21:29:59,371 ! IOError: [Errno 2] No such file or directory: '/home/linaro/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint_NavbarTemp-0.12.dist-info/METADATA'
> 2019-04-30 21:29:59,372 ! ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/linaro/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint_NavbarTemp-0.12.dist-info/RECORD'
> 2019-04-30 21:29:59,372 ! 
> 2019-04-30 21:29:59,882 > Building wheel for OctoPrint-NavbarTemp (setup.py): finished with status 'done'
> 2019-04-30 21:29:59,885 > Stored in directory: /tmp/pip-ephem-wheel-cache-vASTMr/wheels/df/3d/05/7c32e9098fc0d557edcff3d9b0667e0abdd69bc5e9682587ef
> 2019-04-30 21:29:59,887 > Successfully built OctoPrint-NavbarTemp
> 2019-04-30 21:29:59,888 > Installing collected packages: OctoPrint-NavbarTemp
> 
> > 
```

**Comment by Cosik** [comment]
@jalanjarosz is problem still visible?

**Comment by jalanjarosz** [comment]
I ended up switching to Debian Stretch with Armbian Linux 4.19.69-rockchip and have no issues using your plug-in.  Not sure if there is something missing in Linaro, but Armbin is working just fine.

**Comment by arekm** [comment]
Please reopen with new data if this no longer works with current version.
